version: "3.4"

services:
    consul:
        image: consul
        container_name: consul
        ports:
            - 8500:8500
        command: "agent -server -bootstrap -ui -client=0.0.0.0"
    
    fabio:
        image: fabiolb/fabio
        ports:
            - 9999:9999
            - 9998:9998
        environment:
            - registry_consul_addr=consul:8500
        depends_on:
            - consul
